### PR TITLE
Update publications.yaml

### PR DESCRIPTION
**Pull request by goncalomordido**

### CODE REVIEW

**Comment by AndreasMadsen** [comment]
@goncalomordido Please confirm that the date is the venue date. Not the ArXiv date.

**Comment by goncalomordido** [comment]
@AndreasMadsen Both workshops were in 2022.

**Comment by goncalomordido** [comment]
The clarification is due to only the year being shown on the website. I updated the date to the CoLLAs workshop nevertheless

**Comment by AndreasMadsen** [comment]
The order of the papers on the website is determined by the date. In the future, we may wish to show more information. The date needs to be correct.

**Pull request merged**
